### ISSUE TITLE
MonolithicDecoder

### ISSUE THREAD

**Issue by Milostep** [roberto-aldera/pose-prediction#1]
Hello! Thank you for your code. 
I have question about these functions: 
from mrg.logging import MonolithicDecoder
from mrg.adaptors.transform import PbSerialisedTransformToPython

Where can I find these functions?

**Comment by roberto-aldera** [comment]
Hey @Milostep, the mrg module is part of the lab's internal code which isn't shared publicly, but it was only used here to parse the radar monolithic files so you should be able to swap that out for another component and still make use of the core code contained here. I'm not actively maintaining this but you're welcome to tinker with it!
